export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
alias chrome='open -a Google\ Chrome'
alias spot='open -a Spotify'
alias mail='open -a Polymail'
alias todo='open -a Todoist'
alias edit='atom'
alias starwars='telnet towel.blinkenlights.nl'
